Creating a group
MadhuriUttarkar/Messenger pull request #9
Opened 2023-08-06 17:07 UTC by MadhuriUttarkar

2023-08-07 20:31 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/util/HibernateUtil.java
> +	public static Session getSession() {
this creates a session for every getSession call ?
How can you optimize to only create a session once at the starting of the app ?
something like singleton pattern ?

2023-08-07 20:32 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/handler/GroupHandler.java
> +	@GET
format the code

2023-08-07 20:32 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +    private String groupMessages;
what is groupMessages ?

2023-08-07 20:32 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +    private String groupAdmin;
is Admin not a profileId ?

2023-08-07 20:33 UTC, dwarakauttarkar reviewed
take a look at comments

2023-08-08 04:00 UTC, MadhuriUttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +    private String groupAdmin;
groupAdmin is the owner of the group

2023-08-08 04:01 UTC, MadhuriUttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +    private String groupMessages;
Messages in the group

2023-08-08 19:36 UTC, dwarakauttarkar approved these changes

2023-08-08 19:45 UTC, dwarakauttarkar requested changes

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +@Table(name = "MessageGroup")
channel or group

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +	@Column(name = "groupid")
id

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +	private String groupName;
name

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +	@Column(name = "groupAdmin")
admin_id

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +	private String groupMessages;
welcome_message

2023-08-08 19:45 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/MessageGroup.java
> +	private Date created;
created_at

2023-08-08 23:53 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/Channel.java
> +	private String created_by;
Is created_by a user ? Then why not use id here ?

2023-08-08 23:53 UTC, dwarakauttarkar commented on src/main/java/org/madhuri/app/message/model/Channel.java
> +	public void setAdmin_id(Long admin_id) {
Method names are never snake case in Java...

2023-08-09 02:46 UTC, dwarakauttarkar approved these changes

2023-08-09 18:13 UTC, merged